# kubectl create cronjob cj --schedule="* * * *" \
# --restart=Never --image=busxbox -- /bin/sh -c "date; sleep 30; date"
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjab-exam
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 500
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjab-container-exam
            image: busybox
            args:
            - "/bin/sh"
            - "-c"
            - "echo 'START';  sleep 10; echo  'END'"
          restartPolicy: Never
