apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainui-canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mainui
      version: canary
  template:
    metadata:
      name: mainui-pod
      labels:
        app: mainui
        version: canary
    spec:
      containers:
      - name: mainui
        image: nginx:1.15
        ports:
        - containerPort: 80
