apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-lab
spec:
  replicas: 3
  selector:
    app: main
  template:
    metadata:
      name: apache
      labels:
        app: main
    spec:
      containers:
      - name: rc-mainui
        image: httpd:2.2
